# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "z0c/windows-2012r2"
  config.vm.box_url = "https://atlas.hashicorp.com/z0c/boxes/windows-2012r2"
  config.vm.communicator = "winrm"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.provision "chef_solo" do |chef|
    chef.log_level = :debug
    chef.cookbooks_path = ["../../cookbooks/custom", "../../cookbooks/market"]
    chef.add_recipe("build-essential")
    chef.add_recipe("ark")
    chef.add_recipe("chef_handler")
    chef.add_recipe("windows")
    chef.add_recipe("chocolatey")
    chef.add_recipe("7-zip")
    chef.add_recipe("winrm")
    chef.add_recipe("java-windows")
    chef.add_recipe("maven-windows")
    chef.add_recipe("embed-mysql")

    chef.json.merge!({
      :maven => { :mirror => "http://apache.mirror.vu.lt", :major => "3", :version => "3.2.5" },
      :winrm => { :limit_mb => 1024 },
      :embed_mysql => { :path => "c:\\source" },
      :chocolatey => { :upgrade => true },
      :java_windows => { :package_name => "jdk7"}
    })
  end

  config.vm.provision "shell" do |s|
    s.inline = "cd c:\\source\\wix-embedded-mysql; mvn clean test -Dtest=SupportedVersionsTest"
    s.privileged = false
  end

end